services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inf24dw1g36/inf24dw1g36_rep1:latest
    depends_on:
      mysql: # Garante que o MySQL esteja pronto antes do Node.js
        condition: service_healthy
    ports:
      - "8080:8080"

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: inf24dw1g36/inf24dw1g36_rep2:latest
    volumes:
      - hotel-mysql-data:/var/lib/mysql # Volume persistente para dados do banco
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  hotel-mysql-data: